stages:
- update-node
pull-latest:
  stage: update-node
  image: alpine/kubectl:latest
  script:
  - echo "node repository update is starting now..."
  - kubectl rollout restart daemonset/kubernetes-manifest-updater -n gitlab
  - kubectl rollout status daemonset/kubernetes-manifest-updater -n gitlab
  - echo "completed"
  tags:
  - Kubernetes