stages:
- update-node
pull-latest:
  stage: update-node
  image: alpine/git:latest
  script:
  - echo "node repository update is starting now..."
  - cd /manifest
  - git config --global --add safe.directory /manifest

  - |
    if [ ! -d ".git" ]; then
      echo "cloning now..."
      git clone $CI_REPOSITORY_URL .
    else
      echo "pulling now..."
      git fetch origin
      git reset --hard origin/main
    fi
  tags:
  - Kubernetes