# hashicorp/terraform:1.15
apiVersion: v1
kind: Namespace
metadata:
  name: terraform

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraform-app
  labels:
    app: terraform
  namespace: terraform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: terraform
  template:
    metadata:
      labels:
        app: terraform
    spec:
      initContainers:
      - name: loader
        image: alpine/git:2.52.0
        args: ["clone", "--branch", "main", "--depth", "1", "$(GIT_URL)", "/app"]
        volumeMounts:
        - name: repository
          mountPath: /app
        env:
        - name: GIT_URL
          valueFrom:
            secretKeyRef:
              name: tf-secret
              key: repo-url

      containers:
      - name: app
        image: hashicorp/terraform:1.15
        workingDir: /app
        command: ["/bin/sh", "-c"]
        args:
        - |
          terraform init
          terraform -install-autocomplete
          sleep 3600
        volumeMounts:
        - name: repository
          mountPath: /app
        env:
        - name: TF_VAR_PROXMOX_VE_ENDPOINT
          valueFrom:
            secretKeyRef:
              name: tf-secret
              key: endpoint
        - name: TF_VAR_PROXMOX_VE_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: tf-secret
              key: api-token
        - name: TF_VAR_PROXMOX_VE_SSH_USERNAME
          valueFrom:
            secretKeyRef:
              name: tf-secret
              key: ssh-username
        - name: TF_VAR_PROXMOX_VE_SSH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tf-secret
              key: ssh-password
        - name: TF_VAR_VM_USERNAME
          valueFrom:
            secretKeyRef:
              name: tf-secret
              key: vm-username
        - name: TF_VAR_VM_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tf-secret
              key: vm-password
      restartPolicy: Always

      volumes:
      - name: repository
        emptyDir: {}
