apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: terraform
  name: vault-connection
spec:
  address: https://vault.vault.svc.cluster.local:8200
  skipTLSVerify: true

---  

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: terraform
  name: terraform-secret
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: terraform
  refreshAfter: 60s
  destination:
    create: true
    name: tf-secret

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace:  terraform
  name: vault-auth
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: terraform
    serviceAccount: terraform-sa
  allowedNamespaces:
    - terraform
