apiVersion: v1
kind: ConfigMap
metadata: 
  name: named-conf
  namespace: bind9
data:
  named.conf.local: |-
    zone "local.newvia.net"{
      type master;
      file "/etc/bind/db.local.newvia.net";
    };
    zone "10.31.172.in-addr.arpa" in{
      type master;
      file "/etc/bind/db.10.31.172";
    };
    zone "20.31.172.in-addr.arpa" in{
      type master;
      file "/etc/bind/db.20.31.172";
    };

  named.conf.options: |-
    options{
      directory "/var/cache/bind";
      allow-query{ 127.0.0.1; 10.0.0.0/8; 172.31.10.0/24; 172.31.20.0/24; };
      allow-recursion { 127.0.0.1; 10.0.0.0/8; 172.31.10.0/24; 172.31.20.0/24; };
      allow-query-cache { 127.0.0.1; 10.0.0.0/8; 172.31.10.0/24; 172.31.20.0/24;};
    };

  db.local.newvia.net: |-
    ;
    ; BIND data file for local.newvia.net
    ;
    $TTL 604800
    @   IN  SOA   local.newvia.net. root.local.newvia.net.(
                  20260629  ; Serial
                  604800    ; Refresh
                  86400     ; Retry
                  2419200   ; Expire
                  604800    ; Negative Cache TTL
    )

    @   IN  NS    ns.local.newvia.net.
    @   IN  A     172.31.10.232
    ns  IN  A     172.31.10.232
    kube-ctrl IN  A   172.31.10.15
    kube-ctrl IN  A   172.31.10.16
    kube-ctrl IN  A   172.31.10.17
    kube IN  A   172.31.10.15
    kube-2 IN  A   172.31.10.16
    kube-3 IN  A   172.31.10.17
    vault   IN  A   172.31.10.230
    ansible-egress  IN  A 172.31.10.251
    gitlab  IN  A   172.31.20.70
    proxmox IN  A   172.31.100.101
    l3sw-1  IN  A   172.31.10.1
    l3sw-1  IN  A   172.31.20.1
    gw      IN  A   172.31.10.254
    gw      IN  A   172.31.20.254

  db.10.31.172: |-
    ;
    ; BIND data file for 172.31.10
    ;
    $TTL 604800
    @   IN  SOA   local.newvia.net. root.local.newvia.net.(
                  20260629  ; Serial
                  604800    ; Refresh
                  86400     ; Retry
                  2419200   ; Expire
                  604800    ; Negative Cache TTL
    )
    @   IN  NS    ns.local.newvia.net.
    1   IN  PTR   l3sw.local.newvia.net.
    15  IN  PTR   kube-2.local.newvia.net.
    16  IN  PTR   kube.local.newvia.net.
    17  IN  PTR   kube-3.local.newvia.net.
    230 IN  PTR   vault.local.newvia.net.
    232 IN  PTR   ns.local.newvia.net.
    251 IN  PTR   ansible-egress.local.newvia.net
    254 IN  PTR   gw.local.newvia.net.

  db.20.31.172: |-
    ;
    ; BIND data file for 172.31.20
    ;
    $TTL 604800
    @   IN  SOA   local.newvia.net. root.local.newvia.net.(
                  20260629  ; Serial
                  604800    ; Refresh
                  86400     ; Retry
                  2419200   ; Expire
                  604800    ; Negative Cache TTL
    )
    @   IN  NS    ns.local.newvia.net.
    1   IN  PTR   l3sw.local.newvia.net.
    70  IN  PTR   gitlab.local.newvia.net.
    101 IN  PTR   proxmox.local.newvia.net.
    254 IN  PTR   gw.local.newvia.net.
