apiVersion: v1
kind: Namespace
metadata:
  name: gitlab

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: gitlab-sa
  namespace: gitlab