apiVersion: v1
kind: Namespace
metadata:
  name: gitlab

---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    kubernetes.io/enforce-mountable-secrets: "true"
  name: gitlab-sa
  namespace: gitlab

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: gitlab
  name: k8s-dir-updater
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: exec-update
  namespace: gitlab
subjects:
- kind: User
  name: gitlab-sa
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: k8s-dir-updater
  apiGroup: rbac.authorization.k8s.io