apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: gitlab
  name: vault-connection
spec:
  address: http://vault.vault.svc.cluster.local:8200
  skipTLSVerify: true

---  

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: gitlab
  name: gitlab-secret
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: gitlab
  refreshAfter: 60s
  destination:
    create: true
    name: gitlab-runner-token

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace:  gitlab
  name: vault-auth
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: gitlab
    serviceAccount: gitlab-sa
  allowedNamespaces:
    - gitlab
