apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: cloudflared
  name: vault-connection
spec:
  address: http://vault.vault.svc.cluster.local:8200
  skipTLSVerify: true

---  

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: cloudflared
  name: cf-tunnel-token
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: cloudflare-tunnel
  refreshAfter: 60s
  destination:
    create: true
    name: tunnel-token

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace:  cloudflared
  name: vault-auth
spec:
  # required configuration
  # VaultConnectionRef of the corresponding VaultConnection CustomResource.
  # If no value is specified the Operator will default to the `default` VaultConnection,
  # configured in its own Kubernetes namespace.
  vaultConnectionRef: vault-connection
  # Method to use when authenticating to Vault.
  method: kubernetes
  # Mount to use when authenticating to auth method.
  mount: kubernetes
  # Kubernetes specific auth configuration, requires that the Method be set to kubernetes.
  kubernetes:
    # role to use when authenticating to Vault
    role: cloudflare
    # ServiceAccount to use when authenticating to Vault
    # it is recommended to always provide a unique serviceAccount per Pod/application
    serviceAccount: cloudflare-sa
  allowedNamespaces:
    - cloudflared
