---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-st2-packs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-st2-virtualenvs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-st2-configs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
