apiVersion: v1
kind: Namespace
metadata:
  name: ansible

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible
  namespace: ansible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible
  template:
    metadata:
      name: ansible
      namespace: ansible
      labels:
        app: ansible
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "ansible"
        vault.hashicorp.com/agent-inject-secret-vault-password: "kv/data/ansible"
        vault.hashicorp.com/agent-inject-template-vault-password: |
          {{- with secret "kv/data/ansible" -}}
          {{ .Data.data.vault-password }}
          {{- end }}
        vault.hashicorp.com/tls-secret: "vault-ha-tls"
        vault.hashicorp.com/ca-cert: "/vault/tls/ca.crt"
    spec:
      serviceAccountName: ansible-sa
      initContainers:
      # Clone Repository
      - name: git-clone
        image: alpine/git:2.52.0
        command: ["/bin/sh", "-c"]
        args:
        - "git clone --branch main --depth 1 $(GIT_URL) /app"
        volumeMounts:
        - name: appdir
          mountPath: "/app"
        env:
          - name: GIT_URL
            valueFrom:
              secretKeyRef:
                name: git-url
                key: repo-url
      containers:
      - name: ansible-executor
        image: alpine/ansible:2.21.0
        command: ["/bin/sh", "-c"]
        args:
        - |
          ansible-galaxy collection install -r /app/requirements.yml && sleep infinity
        env:
        - name: ANSIBLE_CONFIG
          value: "/app/ansible.cfg"
        - name: ANSIBLE_VAULT_PASSWORD_FILE
          value: "/vault/secrets/vault-password"
        volumeMounts:
        - name: appdir
          mountPath: "/app"
        workingDir: "/app"
      volumes:
      - name: appdir
        emptyDir: {}
      - name: secretdir
        emptyDir: {}

