---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: for-stackstorm
  namespace: ansible
roleRef:
  kind: Role
  name: ansible-handler
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: stackstorm-ha
  namespace: stackstorm

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ansible-handler
  namespace: ansible
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "watch", "create"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch"]
