apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultConnection
metadata:
  namespace: wireguard
  name: vault-connection
spec:
  address: http://vault.vault.svc.cluster.local:8200
  skipTLSVerify: true

---  

apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  namespace: wireguard
  name: wireguard-secret
spec:
  vaultAuthRef: vault-auth
  mount: kv
  type: kv-v2
  path: wireguard
  refreshAfter: 60s
  destination:
    create: true
    name: wg-secret

---
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultAuth
metadata:
  namespace: wireguard
  name: vault-auth
spec:
  vaultConnectionRef: vault-connection
  method: kubernetes
  mount: kubernetes
  kubernetes:
    role: wireguard
    serviceAccount: wireguard-sa
  allowedNamespaces:
    - wireguard
